# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false

# Multi-Loader Configuration
enabled_platforms=fabric,neoforge

# Minecraft version target
minecraft_version=26.1
minecraft_version_publish_range=[26.1,26.2)

# Fabric Properties
# Check these on https://fabricmc.net/develop
fabric_loader_version=0.18.6
fabric_api_version=0.145.1+26.1

# NeoForge version for target Minecraft version
# Check these on https://neoforged.net/
neoforge_version=26.1.0.19-beta

# Architectury Properties (for multiloader support)
architectury_plugin_version=3.5-SNAPSHOT
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=3.3.0-DEV-a4
maven_group=win.demistorm.stormiespiders
mod_id=stormiespiders
mod_name=Stormie's Spiders
mod_author=Halfstorm
license=GNU-LGPL v2.1
credits=TheCyberBrick and Nyfaria
description=You wish spiders would actually climb properly? \
  Stormie's Spiders enables spiders to walk along walls and ceilings and it improves their AI \
  so that they can find their way around almost any obstacle!

# Mod Menu for Fabric (optional dependency)
modmenu_version=18.0.0-alpha.8
