# Project
version=3.1.0
group=win.demistorm.stormiespiders
java_version=21

# Common
mod_name=Stormie's Spiders
mod_author=Halfstorm
mod_id=stormiespiders
license=GNU-LGPL v2.1
credits=TheCyberBrick and Nyfaria
description=You wish spiders would actually climb properly? \
  Stormie's Spiders enables spiders to walk along walls and ceilings and it improves their AI \
  so that they can find their way around almost any obstacle!
# For version range, [1.21.6, 1.21.8) as an example. [ versions )
# For single, just [version]
minecraft_version_range=[1.21.11]

# Parchment version (check https://parchmentmc.org/docs/getting-started)
mappings_channel=parchment
parchment_version=1.21.10:2025.10.12

# Minecraft version
minecraft_version=1.21.11

# Fabric version (check https://fabricmc.net/develop/)
fabric_version=0.139.4+1.21.11
fabric_loader_version=0.18.1

# NeoForge version (check https://neoforged.net/)
neoforge_version=21.11.3-beta
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Enabled loaders
enabled_platforms=fabric,neoforge

# Architectury Properties
architectury_plugin_version=3.4-SNAPSHOT
loom_version=1.13-SNAPSHOT

# Mod Menu for Fabric (optional dependency)
modmenu_version=14.0.0
